import { writable } from 'svelte/store';

// Gallery
export const isGalleryOpen = writable(false);
export const galleryIndex = writable(0);

export const galleryStore = {
	open: (idx = 0) => {
		galleryIndex.set(idx);
		isGalleryOpen.set(true);
	},
	close: () => isGalleryOpen.set(false)
};

export const galleryImages = [
	{ src: 'outside/1.webp', category: 1 },
	{ src: 'outside/2.webp', category: 1 },
	{ src: 'outside/3.webp', category: 1 },
	{ src: 'outside/4.webp', category: 1 },
	{ src: 'outside/5.webp', category: 1 },
	{ src: 'outside/6.webp', category: 1 },
	{ src: 'outside/7.webp', category: 1 },
	{ src: 'outside/8.webp', category: 1 },
	{ src: 'outside/9.webp', category: 1 },
	{ src: 'outside/10.webp', category: 1 },
	{ src: 'outside/11.webp', category: 1 },
	{ src: 'outside/12.webp', category: 1 },
	{ src: 'outside/13.webp', category: 1 },
	{ src: 'outside/14.webp', category: 1 },
	{ src: 'outside/15.webp', category: 1 },
	{ src: 'outside/16.webp', category: 1 },
	{ src: 'outside/17.webp', category: 1 },
	{ src: 'outside/18.webp', category: 1 },
	{ src: 'outside/19.webp', category: 1 },
	{ src: 'outside/20.webp', category: 1 },
	{ src: 'outside/21.webp', category: 1 },
	{ src: 'outside/22.webp', category: 1 },
	{ src: 'outside/23.webp', category: 1 },
	{ src: 'outside/24.webp', category: 1 },
	{ src: 'outside/25.webp', category: 1 },
	{ src: 'outside/26.webp', category: 1 },
	{ src: 'outside/27.webp', category: 1 },
	{ src: 'outside/28.webp', category: 1 },
	{ src: 'outside/29.webp', category: 1 },
	{ src: 'outside/30.webp', category: 1 },
	{ src: 'outside/31.webp', category: 1 },
	{ src: 'outside/32.webp', category: 1 },
	{ src: 'outside/33.webp', category: 1 },
	{ src: 'outside/34.webp', category: 1 },
	{ src: 'outside/35.webp', category: 1 },
	{ src: 'outside/36.webp', category: 1 },
	{ src: 'outside/37.webp', category: 1 },
	{ src: 'outside/38.webp', category: 1 },
	{ src: 'outside/39.webp', category: 1 },
	{ src: 'outside/40.webp', category: 1 },
	{ src: 'outside/41.webp', category: 1 },
	{ src: 'outside/42.webp', category: 1 },
	{ src: 'outside/43.webp', category: 1 },
	{ src: 'outside/44.webp', category: 1 },
	{ src: 'outside/45.webp', category: 1 },
	{ src: 'outside/46.webp', category: 1 },
	{ src: 'outside/47.webp', category: 1 },
	{ src: 'outside/48.webp', category: 1 },

	{ src: 'first_floor/1.webp', category: 2 },
	{ src: 'first_floor/2.webp', category: 2 },
	{ src: 'first_floor/3.webp', category: 2 },
	{ src: 'first_floor/4.webp', category: 2 },
	{ src: 'first_floor/5.webp', category: 2 },
	{ src: 'first_floor/6.webp', category: 2 },
	{ src: 'first_floor/7.webp', category: 2 },
	{ src: 'first_floor/8.webp', category: 2 },
	{ src: 'first_floor/9.webp', category: 2 },
	{ src: 'first_floor/10.webp', category: 2 },
	{ src: 'first_floor/11.webp', category: 2 },
	{ src: 'first_floor/12.webp', category: 2 },
	{ src: 'first_floor/13.webp', category: 2 },
	{ src: 'first_floor/14.webp', category: 2 },
	{ src: 'first_floor/15.webp', category: 2 },
	{ src: 'first_floor/16.webp', category: 2 },
	{ src: 'first_floor/17.webp', category: 2 },
	{ src: 'first_floor/18.webp', category: 2 },
	{ src: 'first_floor/19.webp', category: 2 },
	{ src: 'first_floor/20.webp', category: 2 },
	{ src: 'first_floor/21.webp', category: 2 },
	{ src: 'first_floor/22.webp', category: 2 },
	{ src: 'first_floor/23.webp', category: 2 },
	{ src: 'first_floor/24.webp', category: 2 },
	{ src: 'first_floor/25.webp', category: 2 },
	{ src: 'first_floor/26.webp', category: 2 },
	{ src: 'first_floor/27.webp', category: 2 },
	{ src: 'first_floor/28.webp', category: 2 },
	{ src: 'first_floor/29.webp', category: 2 },
	{ src: 'first_floor/30.webp', category: 2 },
	{ src: 'first_floor/31.webp', category: 2 },
	{ src: 'first_floor/32.webp', category: 2 },
	{ src: 'first_floor/33.webp', category: 2 },
	{ src: 'first_floor/34.webp', category: 2 },
	{ src: 'first_floor/35.webp', category: 2 },
	{ src: 'first_floor/36.webp', category: 2 },
	{ src: 'first_floor/37.webp', category: 2 },
	{ src: 'first_floor/38.webp', category: 2 },
	{ src: 'first_floor/39.webp', category: 2 },
	{ src: 'first_floor/40.webp', category: 2 },
	{ src: 'first_floor/41.webp', category: 2 },
	{ src: 'first_floor/42.webp', category: 2 },
	{ src: 'first_floor/43.webp', category: 2 },
	{ src: 'first_floor/44.webp', category: 2 },
	{ src: 'first_floor/45.webp', category: 2 },
	{ src: 'first_floor/46.webp', category: 2 },
	{ src: 'first_floor/47.webp', category: 2 },
	{ src: 'first_floor/48.webp', category: 2 },
	{ src: 'first_floor/49.webp', category: 2 },
	{ src: 'first_floor/50.webp', category: 2 },
	{ src: 'first_floor/51.webp', category: 2 },

	{ src: 'second_floor/1.webp', category: 3 },
	{ src: 'second_floor/2.webp', category: 3 },
	{ src: 'second_floor/3.webp', category: 3 },
	{ src: 'second_floor/4.webp', category: 3 },
	{ src: 'second_floor/5.webp', category: 3 },
	{ src: 'second_floor/6.webp', category: 3 },
	{ src: 'second_floor/7.webp', category: 3 },
	{ src: 'second_floor/8.webp', category: 3 },
	{ src: 'second_floor/9.webp', category: 3 },
	{ src: 'second_floor/10.webp', category: 3 },
	{ src: 'second_floor/11.webp', category: 3 },
	{ src: 'second_floor/12.webp', category: 3 },
	{ src: 'second_floor/13.webp', category: 3 },
	{ src: 'second_floor/14.webp', category: 3 },
	{ src: 'second_floor/15.webp', category: 3 },
	{ src: 'second_floor/16.webp', category: 3 },
	{ src: 'second_floor/17.webp', category: 3 },
	{ src: 'second_floor/18.webp', category: 3 },
	{ src: 'second_floor/19.webp', category: 3 },
	{ src: 'second_floor/20.webp', category: 3 },
	{ src: 'second_floor/21.webp', category: 3 },
	{ src: 'second_floor/22.webp', category: 3 },
	{ src: 'second_floor/23.webp', category: 3 },
	{ src: 'second_floor/24.webp', category: 3 },
	{ src: 'second_floor/25.webp', category: 3 },
	{ src: 'second_floor/26.webp', category: 3 },
	{ src: 'second_floor/27.webp', category: 3 },
	{ src: 'second_floor/28.webp', category: 3 },
	{ src: 'second_floor/29.webp', category: 3 },
	{ src: 'second_floor/30.webp', category: 3 },
	{ src: 'second_floor/31.webp', category: 3 },
	{ src: 'second_floor/32.webp', category: 3 },
	{ src: 'second_floor/33.webp', category: 3 },
	{ src: 'second_floor/34.webp', category: 3 },
	{ src: 'second_floor/35.webp', category: 3 },
	{ src: 'second_floor/36.webp', category: 3 },
	{ src: 'second_floor/37.webp', category: 3 },
	{ src: 'second_floor/38.webp', category: 3 },
	{ src: 'second_floor/39.webp', category: 3 },
	{ src: 'second_floor/40.webp', category: 3 },
	{ src: 'second_floor/41.webp', category: 3 },
	{ src: 'second_floor/42.webp', category: 3 },

	{ src: 'third_floor/1.webp', category: 4 },
	{ src: 'third_floor/2.webp', category: 4 },
	{ src: 'third_floor/3.webp', category: 4 },
	{ src: 'third_floor/4.webp', category: 4 },
	{ src: 'third_floor/5.webp', category: 4 },
	{ src: 'third_floor/6.webp', category: 4 },
	{ src: 'third_floor/7.webp', category: 4 },
	{ src: 'third_floor/8.webp', category: 4 },
	{ src: 'third_floor/9.webp', category: 4 },
	{ src: 'third_floor/10.webp', category: 4 },
	{ src: 'third_floor/11.webp', category: 4 },
	{ src: 'third_floor/12.webp', category: 4 },
	{ src: 'third_floor/13.webp', category: 4 },
	{ src: 'third_floor/14.webp', category: 4 },
	{ src: 'third_floor/15.webp', category: 4 },
	{ src: 'third_floor/16.webp', category: 4 },
	{ src: 'third_floor/17.webp', category: 4 },
	{ src: 'third_floor/18.webp', category: 4 },
	{ src: 'third_floor/19.webp', category: 4 },
	{ src: 'third_floor/20.webp', category: 4 }
];

// Modal
export const isModalOpen = writable(false);
export const modalStore = {
	open: () => isModalOpen.set(true),
	close: () => isModalOpen.set(false)
};

// Menu
export const isMenuOpen = writable(false);
export const menuStore = {
	open: () => isMenuOpen.set(true),
	close: () => isMenuOpen.set(false)
};
